name: Build and Run Java Application

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' 
      
    - name: Build Java Application
      run: |
        mkdir bin
        javac -d bin src/*.java
        
    - name: Run Java Application
      run: java -cp bin JavaApplicationSum  
